//
//  MMResponseToCSV.h
//  Multimedia
//
//  Created by Thomas Sherwood on 30/12/2013.
//  Copyright (c) 2013 Thomas Sherwood. All rights reserved.
//

#import <Foundation/Foundation.h>

@class MultimediaResponse, MediaResponse;

/// Provides the capability to convert model objects into CSV.
@interface MMResponseToCSV : NSObject

/**
 * Gets the header string for a CSV document generated by this class
 * @param an NSString containing the column headers
 */
+ (NSString*)csvHeader;

/**
 * Converts a collection of MultimediaResponse objects into CSV data
 * @param responses the set of MultimediaResponse objects
 * @return an NSData object containing the CSV data
 */
+ (NSData*)createCSVDataForComplexAggregation:(NSArray*)responses;

/**
 * Converts a single MultimediaResponse into CSV data
 * @param response the MultimediaResponse to convert to CSV
 * @param NSData the CSV data from the response
 */
+ (NSData*)createCSVDataForAggregation:(MultimediaResponse*)response;

/**
 * Converts a single MediaResponse into CSV
 * @param response the MediaResponse to convert to CSV
 * @param NSData the CSV data from the response
 */
+ (NSData*)createCSVDataForResponse:(MediaResponse*)response;

@end
